### PR TITLE
Summary bug fix

### LINKED ISSUE #172: 🐞 [Bug]: solution subscription crashes because it cannot parse the summary sometimes
### What happened?

```
Error:
   0: solution subscription crashed
   1: couldn't parse summary
   2: TOML parse error at line 1, column 1
   2:   |
   2: 1 |
   2:   | ^
   2: missing field `initial_plotting_finished`
   2:

Location:
   src/summary.rs:161
```

### Version

0.3.0 and 0.3.1

### platform

- [X] linux
- [X] windows
- [X] macos

### Expected behavior

The parsing shouldn't have failed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ozgunozerk**
Closes #172

### CODE REVIEW

File: src/summary.rs [hunk 1]
```diff
@@ -143,15 +143,11 @@ impl SummaryFilePointer {
         let new_summary = toml::to_string(&summary).context("Failed to serialize Summary")?;
 
         let guard = self.file.lock().await;
-        OpenOptions::new()
-            .write(true)
-            .truncate(true)
-            .open(&*guard)
-            .await?
-            .write_all(new_summary.as_bytes())
-            .await?;
```
Comment (i1i1) [inline src/summary.rs:152]: It flushes everything at close I think

Comment (ozgunozerk) [reply src/summary.rs:152]: we can't close though xD

**Review by i1i1 — APPROVED** [review]
